# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'OprationDownload' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  
  pod 'AFNetworking', '~> 4.0.1'

  # Pods for OprationDownload

  target 'OprationDownloadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OprationDownloadUITests' do
    # Pods for testing
  end

end
